# Generated by Django 5.1.11 on 2025-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(unique=True)),
                ('chat_title', models.CharField(max_length=255)),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='polluser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='polluser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='server.group'),
        ),
    ]
