# Generated by Django 5.1.11 on 2025-07-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_group_polluser_telegram_id_alter_polluser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='telegram_id',
        ),
    ]
